aboutfront/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views
#Пути для url-маршрутизации приложения: все записи на главной страницы, конкретная запись по id и путь для добавления комментариев по id
urlpatterns = [path('', views.PostView.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments')]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField('Заголовок', max_length= 200)
    description = models.TextField('Текст')
    author = models.CharField('Имя автора', max_length= 200)
    date = models.DateField('Дата')
    img = models.ImageField('Изображение', upload_to='image/', max_length=200, blank=True)

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)
#Функция обеспечивает читаемое представление для админки.
    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post
from .form import CommentsForm


# Представление для отображения списка всех записей
class PostView(View):
    def get(self, request):
        # Получаем все записи из базы данных
        posts = Post.objects.all()
        # Отображаем список записей на странице
        return render(request, 'blog/blog.html', {'post_list': posts})


# Представление для отображения конкретной записи
class PostDetail(View):
    def get(self, request, pk):
        # Получаем конкретную запись по её id
        post = Post.objects.get(id = pk)
        # Отображаем конкретную запись уже на другой странице
        return render(request, 'blog/blog_detail.html', {'post': post})

# Представление для добавления комментария к конкретной записи
class AddComments(View):

    def post(self, request, pk):
        # Создаем форму на основе данных, полученных из POST-запроса
        form = CommentsForm(request.POST)
        # Проверяем, валидна ли форма
        if form.is_valid():
            # Создаем объект комментария, но не сохраняем его в базе данных пока
            form = form.save(commit=False)
            # Присваиваем комментарию id записи, к которой он относится
            form.post_id = pk
            # Сохраняем комментарий в базе данных
            form.save()
        # Перенаправляем пользователя обратно к записи, к которой он добавил комментарий
        return redirect(f'/{pk}')

blog/templates/blog/blog.html
{% load static %}
<html>
<head>
   <title>About front-end</title>
   <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
   <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" media="all" />


	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Frontend-программист</a></li>
			    <li><a href="/admin">Админка</a></li>

			</ul>
		</div>

		<div id="main">
   			<div id="content" class="left">

      			<div class="projects">
         			<h3>Записи</h3>
         			{% for post in post_list %}
         			<div class="item">
            			<div class="image left">
               				<img src="{{ post.img.url }}" width="150px" height = "100px"/>
            			</div>
						<div class="text left">
               				<h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
               				<p>{% if post.description|length > 120 %}{{ post.description|slice:":120" }}...{% else %}{{ post.description }}{% endif %}</p>
               				<p>Автор: {{ post.author }}</p>
            			</div>
            			<div class="cl"> </div>
         			</div>
          			{% endfor %}
     			 </div>
   			</div>


			<div class="cl"> </div>
		</div>
	</div>
		<div id="footer">
		<p class="copy right">Исмагилов Данил РИ-220945</p>
	</div>

</div>
</body>
</html>

blog/templates/blog/blog_detail.html
{% load static %}
<html>
<head>
   <title>Frontend-программист</title>
   <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
   <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" media="all" />


</head>
<body>
<div class="shell">
	<div class="border">

		<div id="navigation">
			<ul>
			    <li><a href="/" class="active">Frontend-программист</a></li>
			    <li><a href="/admin">Админка</a></li>

			</ul>
		</div>

		<div id="main">
   			<div id="content" class="left">

      			<div class="projects">
         			<h3>{{ post.title }}</h3>
                  <p align="center">
                    <img src="{{ post.img.url }}" width="80%"/>
                  </p>
         			<div class="item">
						<div class="text left">
               				<p>{{ post.description|linebreaksbr }}</p>
               				<p> <br>Автор<br>{{ post.author }}</p>
            			</div>
            			<div class="cl"> </div>
         			</div>
     			 </div>
   			</div>
			<div>
			</div>
			<div class="form-comment">
				<h3>Оставить комментарий</h3>
				<div>
					<form action="{% url 'add_comments' post.id %}" method="post">
						{% csrf_token %}
						<div>
							<label>Ваш комментарий</label>
							<textarea name="text_comments"></textarea>
						</div>
						<div>
							<label>Ваше имя *</label>
							<input type="text" name="name">
						</div>
						<div><input type="submit"></div>
					</form>
				</div>
			</div>
			<div>
				{% for comment in post.comments_set.all %}
				<div class="view-comment">
					<h4>{{ comment.name }}</h4>
					<p>
						{{ comment.text_comments }}
					</p>
				</div>
				{% endfor %}
			</div>


			<div class="cl"> </div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Исмагилов Данил РИ-220945 </p>
	</div>
</div>
</body>
</html>